env:
  browser: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - 0
    - always
  no-var: error
  no-unused-vars: 1
  no-cond-assign: 2
  block-scoped-var: 2
  class-methods-use-this: 2
  eqeqeq: 2
  no-div-regex: 2
  no-fallthrough: 2
  no-multi-spaces: 2
  yoda: 2
  no-undef-init: 2
  array-bracket-spacing: 2
  camelcase: 2
  brace-style: 2
  comma-dangle: 2
  comma-spacing: 2
  computed-property-spacing: 2
  func-call-spacing: 2
  func-style: 2
  max-len:
    - 1
    - 80
  no-console: 1
  no-mixed-spaces-and-tabs: 2
  arrow-spacing: 2
  prefer-const: 2
  prefer-template: 2
